### ISSUE TITLE
Action seems to be broken

### ISSUE THREAD

**Issue by elliothershberg** [snakemake/snakemake-workflow-catalog#1]
Hi @johanneskoester ! This is a really great resource for Snakemake developers 😃 

I recently added "workflow" to the README of https://github.com/beliveau-lab/PaintSHOP_pipeline to get it picked up by this list, and when I checked back I noticed that the action to generate the catalog seems to be failing right now:

https://github.com/snakemake/snakemake-workflow-catalog/actions/runs/492814135

Just a heads up. Thanks again for the great resource, and I'm excited to see our pipeline end up in there soon 👍

**Comment by johanneskoester** [comment]
Sorry, I missed the failed action (parental leave). Should be fixed now and your workflow should show up in the next few hours.
