### ISSUE TITLE
Snakefile detection

### ISSUE THREAD

**Issue by AntonieV** [snakemake/snakemake-workflow-catalog#10]
Hi @johanneskoester,

thanks for implementing this catalog, this is a great idea! 
I noticed that the RADSeq workflow does not appear there. At first I thought that the repository is not small enough and so I removed the results files. But it still did not appear at this state: 
https://github.com/AntonieV/NodeRAD/commit/3a6c2244b3c0f6cf5521f33bd77d66a063388092

According to the rules for inclusion the repository may also contains the Snakefile outside the workflow directory. But only when I moved the Snakefile to workflow/Snakefile two weeks later, the workflow appeared in the catalog:

https://github.com/AntonieV/NodeRAD/commit/9546cbcb14abb0c20df1a91c6775da2219a113ae

Thanks and best regards, 
Antonie

**Comment by johanneskoester** [comment]
Fixed in the meantime.
