### ISSUE TITLE
Requirements satisfied (?) but my workflow does not appear in the workflow catalog

### ISSUE THREAD

**Issue by felixleopoldo** [snakemake/snakemake-workflow-catalog#13]
Hi, 

I have created a Snakemake workflow [https://github.com/felixleopoldo/benchpress](https://github.com/felixleopoldo/benchpress) called benchpress for benchmarking structure learning algorithms for graphical models. I think it should satisfy the requirements for showing up at the snakemake workflow catalog ([https://snakemake.github.io/snakemake-workflow-catalog/](https://snakemake.github.io/snakemake-workflow-catalog/)) but is doesnt. Do you perhaps know what could be the problem? Maybe I missed something.

Thanks in advance!

Felix

**Comment by johanneskoester** [comment]
Hi @felixleopoldo thanks for reporting. So there must be a problem with the github search. The catalog searches for repos with the  words snakemake and workflow in the readme. However, this does not seem to lead to your repo, although I see the words in your readme. Weirdly, also trying other, more specific words from your readme does not bring me to your repo. For example, try this: https://github.com/search?q=Benchpress+structure+overview+in%3Areadme.

Your repo does not show up for some reason. I have no idea why though. If you can give me any hint, I'd be happy to apply a fix here.

**Comment by johanneskoester** [comment]
The only thing I noticed which might differ in your readme is that you have HTML code in it. Maybe github refuses to index such readmes for searching?

**Comment by felixleopoldo** [comment]
Hi Johannes,
Thank you very much for your answer. I see now that there is some problem with searching in my readme. I will have to look into it further. However, searching for words in the description seems to work fine. Would it make sense for you to also include repos that have snakemake and workflow in the description?

**Comment by felixleopoldo** [comment]
Hi, again Johannes,

I saw that I had an unclosed <![CDATA tag in my readme which was the error. I can now search with in:readme. Thanks a lot for your help!

**Comment by johanneskoester** [comment]
Thanks!
