### ISSUE TITLE
Missing repository?

### ISSUE THREAD

**Issue by rbpatt2019** [snakemake/snakemake-workflow-catalog#15]
Hi all, thanks for maintaining this excellent resources!

I have a question about how repositories are found. I have a repository (https://github.com/IMS-Bio2Core-Facility/polya_liftover) that, to the best of my knowledge, should meet the requirements for "Standardised Usage" - it has the necessary title in the README, a `workflow/Snakefile`, etc. It was originally private (professional obligations) though about 2 weeks ago I made it public.  Yet, I can't find it in the catalogue regardless of whether I look in standardised usage. I doubled checked that the search would return correctly (https://github.com/search?q=polya_liftover+snakemake+workflow+in%3AREADME.md), and it is, so I'm fairly confident that it should be hit by the catalogue's search. I can see from the cron job in the GitHub Action that it should run every day at 0500, so I'm a bit surprised it hasn't been found. 

I'm a big fan of the standardised installation instructions you provide, and was hoping to be able to link out to them in a manuscript I'm preparing for publication. If I'm missing something obvious in my repository structure, or can provide anything else to help, please let me know! Cheers 👍

**Comment by johanneskoester** [comment]
Thanks for reporting! I am checking this, maybe I have found a bug that is fixed in this run already: https://github.com/snakemake/snakemake-workflow-catalog/runs/4958031298?check_suite_focus=true

**Comment by johanneskoester** [comment]
Fixed! Only thing I noticed is that somehow github does not properly find your license. The catalog does not process this itself, it just uses a shields.io badge for that purpose. Maybe it is because of the .md extension? Or something with the license text.
