### ISSUE TITLE
feat: storing snakemake workflows in a subdirectory of a repository

### ISSUE THREAD

**Issue by aryarm** [snakemake/snakemake-workflow-catalog#18]
There have been times where I've created a Snakemake workflow that isn't the main content in a repository.

In those cases, it would be nice if there was a way to specify that my Snakemake workflow is in a subdirectory of my repository. Let's say, for example, that I place everything in a subdirectory named `snakemake/`:

```
repository
├── .snakemake-workflow-catalog.yml
├── --other files and directories--
└── snakemake
    ├── README.md
    ├── results
    ├── resources
    ├── config
    │   ├── README.md
    │   └── config.yml
    └── workflow
        ├── rules
        ├── envs
        ├── notebooks
        └── scripts
```

**Comment by johanneskoester** [comment]
I hear you, on the other hand, the purpose of this catalog is standardization. Ideally, every Snakemake workflow repo should look the same, such that people can immediately find their way. Hence, I think I have to disagree on this feature.

**Comment by aryarm** [comment]
Ok, thanks for considering it!
