### ISSUE TITLE
Workflow not included, unclear why

### ISSUE THREAD

**Issue by semenko** [snakemake/snakemake-workflow-catalog#20]
I can't quite figure out why my workflow isn't included, despite (I think) following the instructions for my pipeline here: https://github.com/semenko/serpent-methylation-pipeline

(I'll try posting the debug comment next...)

**Comment by semenko** [comment]
Agreed! Thought not sure why it doesn't show in the standaridzed usage category yet…

**Comment by uniqueg** [comment]
Just a guess, but maybe the `.snakemake-workflow-catalog.yml` file is considered invalid? Maybe try to remove the `mandatory-flags:` section, as you don't give any actual values. And just to be on the safe side, I would probably also remove all the comments.

As a reference, our [ZARP](https://github.com/zavolanlab/zarp) workflow was included under "Standardized usage" with [this](https://github.com/zavolanlab/zarp/blob/520a3de4be829c7e070f2a99c3893e6fdefddc08/.snakemake-workflow-catalog.yml) config file.
