### ISSUE TITLE
GitHub action generate catalogue fails

### ISSUE THREAD

**Issue by DavideBrex** [snakemake/snakemake-workflow-catalog#22]
Hi all,
I think there is a problem with the generation of the catalogue. The github action fails, and the last success is of two months ago:

![errorCatalog](https://github.com/snakemake/snakemake-workflow-catalog/assets/48018596/2f792003-ccd9-4abc-862a-eaea1a5c7476)

**Comment by johanneskoester** [comment]
You are right! I will investigate it now.
