### ISSUE TITLE
Change usage text

### ISSUE THREAD

**Issue by niekwit** [snakemake/snakemake-workflow-catalog#23]
I am wondering how one would change the text that shows up (Step 1-5) when you click on the usage button in the workflow catalog: 

![IMG_3931](https://github.com/snakemake/snakemake-workflow-catalog/assets/41302859/4622a36e-e79e-4dee-b733-f5936f4918c4)
![IMG_3932](https://github.com/snakemake/snakemake-workflow-catalog/assets/41302859/a77df7bb-137d-4ab9-a84f-4f1b7af5d5c1)

I have checked in existing repos but cannot find a file that has this text.

Thank you for making this catalog!

**Comment by johanneskoester** [comment]
The text is generated automatically. It is the same for all workflows. You can find it here: 
https://github.com/snakemake/snakemake-workflow-catalog/blob/fa944f2b1fbf769781e3ea2aa724aeff9a4a7fb6/index.html#L185

PRs with improvements are very welcome.
