### ISSUE TITLE
stars shown in catalogue are not updating

### ISSUE THREAD

**Issue by franciscozorrilla** [snakemake/snakemake-workflow-catalog#24]
Hello, just reporting a small bug: I noticed that the actions are no longer failing in this repo, but the stars have not been updating for the repos shown in the catalogue website.

Best,
Francisco

**Comment by johanneskoester** [comment]
Good point, we should fetch them dynamically using a shields badge like this:
![GitHub Repo stars](https://img.shields.io/github/stars/snakemake-workflows/dna-seq-varlociraptor)

**Comment by johanneskoester** [comment]
The problem is that this then does not allow to use them for sorting.

**Comment by franciscozorrilla** [comment]
looks like the issue has been solved, thanks!
