### ISSUE TITLE
Workflow not included even after following the guidelines

### ISSUE THREAD

**Issue by deliaBlue** [snakemake/snakemake-workflow-catalog#25]
The [MIRFLOWZ](https://github.com/zavolanlab/mirflowz) workflow does not appear in the _Standardized workflows_ section nor passes the test even after making the appropriate changes.

**Comment by johanneskoester** [comment]
Thanks for reporting. I will look into this. I think github api usage currently takes a bit too long for so many workflows, so that not all of them get updated. I will see whether I can split things up into subsequent jobs.

**Comment by m-jahn** [comment]
May I hijack this issue here because I have the exact same problem.
Our workflow https://github.com/MPUSP/snakemake-crispr-guides follows all the best practices from what I can see, but is not included in the standardized usage section.

**Comment by m-jahn** [comment]
Any update on this?
I think a main and recurring problem is that it's not clearly (enough) defined what needs to be done to pass "standardized usage".

That said I think this is really a great resource, and motivates to build standardized workflows.

**Comment by KasperSkytte** [comment]
I'm trying to get my workflow into the catalog for the first time too. So I will try this:
/catalog test repo cmc-aau/nanopore_16Samp

**Comment by KasperSkytte** [comment]
@johanneskoester looks like no new workflows will ever be added until you take a look at it :) No new workflows in the catalogue for almost two months now.

**Comment by johanneskoester** [comment]
Ok, sorry. I will try to fix it today.

**Comment by johanneskoester** [comment]
Ok, should work again. An update is currently running. I keep this open for now until we are sure it is fixed.

**Comment by johanneskoester** [comment]
I think it works again. All the workflows that are mentioned here are now already visible in the online catalog. Feel free to reopen if the problem still occurs.
