### ISSUE TITLE
Still updating? 

### ISSUE THREAD

**Issue by mrvollger** [snakemake/snakemake-workflow-catalog#9]
Hello,

Thanks for making this, I think this is a great idea! 

But is the catalog still being updated? I have a few repos that I would expect to see or that are out of date. 

It's possible that I am just missing some requirement, in which case it would be kinda cool to know in which ways my repos did not meet the requirements. 

github.com/mrvollger/rustybam
https://github.com/mrvollger/StainedGlass
https://github.com/mrvollger/PhaseONT
https://github.com/mrvollger/SmkTemplate

Thanks,
Mitchell

**Comment by johanneskoester** [comment]
Woops, sorry. There was an error when parsing the .snakemake-workflow-catalog.yml in one repo, which led to a crash in the entire process. This should now be fixed. Nevertheless, we should add a stats page that shows the status and potential problems with each considered repo.

**Comment by johanneskoester** [comment]
Fixed in commit e4474192585708df65534a6059dff900deff0bf3.
